### ISSUE TITLE
Failed to activate the code-links package

### ISSUE THREAD

**Issue by tomwganem** [AsaAyers/code-links#10]
[Enter steps to reproduce below:]
1. activate package

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [code-links](https://github.com/AsaAyers/code-links) package, v0.3.8
### Stack Trace

Failed to activate the code-links package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.onProvidersChanged (/Users/tomwganem/.atom/packages/code-links/lib/code-links.js:140:24)
  at Object.consumeLinkProviderV0 (/Users/tomwganem/.atom/packages/code-links/lib/code-links.js:128:14)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:34)
  at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:48:18)
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:350:69)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:225:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:276:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -3:45.1.0 core:backspace (atom-text-editor.editor)
     -3:43.5.0 core:move-right (atom-text-editor.editor)
     -3:39 core:copy (atom-text-editor.editor)
     -3:37.7.0 editor:newline (atom-text-editor.editor)
     -3:37.5.0 core:paste (atom-text-editor.editor)
  2x -3:32.8.0 core:move-up (atom-text-editor.editor)
  4x -3:32.2.0 core:move-left (atom-text-editor.editor)
     -3:31.1.0 core:backspace (atom-text-editor.editor)
     -3:29.8.0 core:move-down (atom-text-editor.editor)
  2x -3:29.6.0 core:move-right (atom-text-editor.editor)
     -3:29.2.0 core:move-down (atom-text-editor.editor)
     -3:29 core:move-right (atom-text-editor.editor)
  7x -3:26.7.0 core:move-down (atom-text-editor.editor)
     -3:23.3.0 core:move-up (atom-text-editor.editor)
  4x -3:22.8.0 core:backspace (atom-text-editor.editor)
  2x -3:08.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "vim-mode",
      "git-plus",
      "Zen",
      "git-difftool",
      "tabular",
      "autoclose-html",
      "minimap-color-highlight",
      "terminal-panel",
      "regex-railroad-diagram",
      "git-show",
      "symbols-view",
      "git-diff-popup",
      "coffee-lint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-ctags, v3.2.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-ruby, v0.1.0
code-links, v0.3.8
coffee-links, v0.1.0
coffee-navigator, v0.0.16
editor-stats, v0.17.0
javascript-snippets, v1.0.0
language-jade, v0.4.0
language-javascript-semantic, v0.1.0
last-cursor-position, v0.9.0
linter, v0.12.1
linter-ruby, v0.1.4
minimap, v4.7.6
minimap-git-diff, v4.1.2
monokai, v0.14.0
ruby-block, v0.3.3
todo-show, v0.8.0

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
>  in 1.0 API Preview Mode ￼

There is your problem. 1.0 removes all depricated APIs and I haven't cleaned that up yet. see #9
