### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bulutmf** [AsaAyers/code-links#21]
I got this error and here is the information.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [code-links](https://github.com/AsaAyers/code-links) package, v0.3.11
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/mfb/.atom/packages/code-links/lib/code-links.js:142

TypeError: undefined is not a function
    at Object.onProvidersChanged (/Users/mfb/.atom/packages/code-links/lib/code-links.js:142:24)
    at Object.consumeLinkProviderV0 (/Users/mfb/.atom/packages/code-links/lib/code-links.js:130:14)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at process._tickCallback (node.js:357:13)
```
### Commands

```
     -0:12.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
code-links, v0.3.11
color-picker, v2.0.11

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
I don't know what caused this, but I'm no longer maintaining code-links. See https://github.com/AsaAyers/code-links/blob/master/README.md for more details
