### ISSUE TITLE
Failed to load the code-links package

### ISSUE THREAD

**Issue by christiansaiki** [AsaAyers/code-links#28]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.3
**Thrown From**: [code-links](https://github.com/AsaAyers/code-links) package, v0.4.0
### Stack Trace

Failed to load the code-links package

```
At Cannot find module 'espree'

Error: Cannot find module 'espree'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/christian/.atom/packages/code-links/lib/javascript-processor.js:4:16)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autosave, v0.23.0
code-links, v0.4.0
file-icons, v1.6.11
indent-guide-improved, v1.4.3
linter, v1.10.0
linter-eslint, v4.0.0

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
It sounds like atom simply failed to install `espree` for some reason. If you really want to stick with code-links, you might try uninstalling and reinstalling it.

From the readme:

> # :rotating_light: Deprecated :rotating_light: 
> 
> If you use `code-links` for scanning JavaScript and not CoffeeScript, you should uninstall it and install [`js-hyperclick`](https://atom.io/packages/js-hyperclick) and [hyperclick](https://atom.io/packages/hyperclick) instead.
